/**
 * CSS hook classes for the front page (Recipe index) — pair with `snippets/recipe-ui.css`.
 * Centralizing names makes layout refactors grep-friendly.
 */
export const FRONTPAGE_LAYOUT = Object.freeze({
    root: "live-root",
    grid: "live__grid",
    sidebar: "live__sidebar",
    main: "live__main",
    sidebarHeader: "live__sidebar-header",
    sidebarTitle: "live__sidebar-title",
    sidebarToggle: "live__sidebar-toggle",
    sidebarContent: "live__sidebar-content",
    sidebarActions: "live__sidebar-actions",
    pageTitle: "live__title",
    indexHeading: "live__index-heading",
    actions: "live__actions",
    section: "live__section",
    sectionHeader: "live__section-header",
    sectionTitle: "live__section-title",
    sectionToggle: "live__section-toggle",
    sectionContent: "live__section-content",
    field: "live__field",
    label: "live__label",
    hint: "live__hint",
    durationBlock: "live__duration-block",
    tagsContainer: "tags-container",
    ingredientSection: "ingredient-filter-wrapper",
    btnApply: "mod-cta live__btn-apply",
    btnReset: "live__btn-reset",
    toolbar: "live__toolbar",
    toolbarLabel: "live__toolbar-label",
    recipeNameInput: "live__recipe-name-input",
    count: "live__count",
    tableHost: "live__table-host",
    empty: "live__empty",
    table: "live__table",
    cellName: "live__cell-name",
    cellThumb: "live__cell-thumb",
    cellRating: "live__cell-rating",
    resultsGroups: "live__results-groups",
    resultsNested: "live__results-nested",
});

export const INGREDIENT_FILTER_LAYOUT = Object.freeze({
    container: "ingredient-filter-container",
    header: "ingredient-filter-header",
    searchWrap: "ingredient-filter-search",
    searchInput: "ingredient-filter-search-input",
    resetWrap: "ingredient-filter-reset",
    list: "ingredient-filter-list",
    empty: "ingredient-filter-empty",
    row: "ingredient-filter-row",
    name: "ingredient-filter-name",
});
