export const INGREDIENT_FRONTMATTER = Object.freeze({
    TAXONOMY: "taxonomy",
    LIQUID: "liquid",
    SINGLE: "single",
    CSS_CLASSES: "cssclasses",
});

export const INGREDIENT_NOTEBOOK = Object.freeze({
    RHO: "liquid",
    SPECIFIC_WEIGHT: "single",
});

export const INGREDIENT_UI_CLASS = "ingredient-ui";

export const INGREDIENTS_FOLDER = "Ingredients";

export const INGREDIENT_LIVE_READ_KEYS = Object.freeze([
    INGREDIENT_FRONTMATTER.TAXONOMY,
    INGREDIENT_FRONTMATTER.LIQUID,
    INGREDIENT_FRONTMATTER.SINGLE,
]);

export const INGREDIENT_LIVE_SUBSCRIPTION_KEYS = Object.freeze([
    INGREDIENT_FRONTMATTER.TAXONOMY,
    INGREDIENT_FRONTMATTER.LIQUID,
    INGREDIENT_FRONTMATTER.SINGLE,
]);

export const INGREDIENT_FRONTMATTER_DEFAULTS = Object.freeze({
    [INGREDIENT_FRONTMATTER.TAXONOMY]: [],
    [INGREDIENT_FRONTMATTER.LIQUID]: 1,
    [INGREDIENT_FRONTMATTER.SINGLE]: 1,
    [INGREDIENT_FRONTMATTER.CSS_CLASSES]: INGREDIENT_UI_CLASS,
});
