/**
 * CSS hook classes for single-recipe pages — pair with `snippets/ui.css`.
 * Shared widgets (MDRC mount, tags row) stay on {@link UI_CLASSES} in `ui.js`.
 */
export const RECIPE_LAYOUT = Object.freeze({
    root: "root",
    layoutRead: "layout-read",
    layoutEdit: "layout-edit",
    toggleBar: "toggle-bar",
    modeLabel: "mode-label",
    toggleActions: "toggle-actions",
    metaStrip: "meta-strip",
    details: "details",
    timingRow: "timing-row",
    sectionHeading: "section-heading",
    readSummary: "read-summary",
    readTimes: "read-times",
    readBody: "read-body",
    readBodySolo: "read-body--solo",
    readAside: "read-aside",
    readMain: "read-main",
    ingredientsContainer: "ingredients-container",
    ingredientRow: "ingredient-row",
    ingredientGroupPanel: "ingredient-group-panel",
    ingredientGroupHeader: "ingredient-group-header",
    ingredientGroupTitle: "ingredient-group-title",
    ingredientGroupActions: "ingredient-group-actions",
    ingredientGroupRows: "ingredient-group-rows",
    ingredientGroupsFooter: "ingredient-groups-footer",
    catalogPicker: "catalog-picker",
    catalogPickerHeader: "catalog-picker-header",
    catalogPickerToggle: "catalog-picker-toggle",
    catalogPickerBody: "catalog-picker-body",
    catalogPickerSearch: "catalog-picker-search",
    catalogPickerSearchInput: "catalog-picker-search-input",
    catalogPickerTree: "catalog-picker-tree",
    catalogPickerNested: "catalog-picker-nested",
    catalogPickerLeaf: "catalog-picker-leaf",
    catalogPickerAddBtn: "catalog-picker-add-btn",
    dragHandle: "drag-handle",
    ingredientGroupRead: "ingredient-group-read",
    addIngredientContainer: "add-ingredient-container",
    personContainer: "person-container",
    durationsContainer: "durations-container",
    durationInputGroup: "duration-input-group",
    durationInputs: "duration-inputs",
    durationViewGroup: "duration-view-group",
    ovenContainer: "oven-container",
    noteContainer: "note-container",
    contentContainer: "content-container",
    sourceContainer: "source-container",
    tagsContainer: "tags-container",
    thumbnailContainer: "thumbnail-container",
    starRating: "recipe-star-rating",
    star: "recipe-star",
    inputField: "input-field",
    viewField: "view-field",
    contentInput: "content-input",
    contentView: "content-view",
});
