/**
 * CSS hook classes for single-recipe pages — pair with `snippets/ui.css`.
 * Shared widgets (MDRC mount, tags row) stay on {@link UI_CLASSES} in `ui.js`.
 */
export const RECIPE_LAYOUT = Object.freeze({
    root: "root",
    layoutRead: "layout-read",
    layoutEdit: "layout-edit",
    toggleBar: "toggle-bar",
    modeLabel: "mode-label",
    toggleActions: "toggle-actions",
    metaStrip: "meta-strip",
    details: "details",
    timingRow: "timing-row",
    sectionHeading: "section-heading",
    readSummary: "read-summary",
    readTimes: "read-times",
    readBody: "read-body",
    readBodySolo: "read-body--solo",
    readAside: "read-aside",
    readMain: "read-main",
    ingredientsContainer: "ingredients-container",
    ingredientRow: "ingredient-row",
    addIngredientContainer: "add-ingredient-container",
    personContainer: "person-container",
    durationsContainer: "durations-container",
    durationInputGroup: "duration-input-group",
    durationInputs: "duration-inputs",
    durationViewGroup: "duration-view-group",
    ovenContainer: "oven-container",
    noteContainer: "note-container",
    contentContainer: "content-container",
    sourceContainer: "source-container",
    tagsContainer: "tags-container",
    inputField: "input-field",
    viewField: "view-field",
    contentInput: "content-input",
    contentView: "content-view",
});
